name = "Less than Compact 2"
author = "Gabe Venberg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f517d4294f1bfb6bd2771e0d5d8337ba8e46a6989823155ffbb696e11318be83"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
