name = "Less than Compact 2"
author = "Gabe Venberg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c62075ef3956347707b4f2ea68a6672ac980589c02d4f259f50de0c5d23f389"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
