name = "Less than Compact 2"
author = "Gabe Venberg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d887bf1830970cdcc8301c6b154a9a6752ff3c493d56aa372b753d6d2b3ef9e8"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
