name = "Less than Compact 2"
author = "Gabe Venberg"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b51e584fdfba152a13d9db9b6f23b326453b1e66996188403496833ac68c2016"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
