ServerEvents.recipes(event => {
    event.recipes.create.compacting('create:experience_nugget', [Fluid.of('create_enchantment_industry:experience', 3)])
    event.recipes.create.compacting('create:limestone', ['minecraft:bone_block', Fluid.water(1000)]).heated()
    event.recipes.create.compacting('minecraft:amethyst_block', ['minecraft:quartz_block', 'minecraft:iron_nugget']).heated()
    event.recipes.create.compacting('minecraft:calcite', ['create:limestone', Fluid.lava(15)])
    event.recipes.create.compacting('minecraft:deepslate', ['minecraft:cobblestone', Fluid.lava(50)])
    event.recipes.create.compacting('minecraft:gilded_blackstone', ['minecraft:blackstone', 'minecraft:gold_ingot', 'minecraft:gold_ingot']).heated()
    event.recipes.create.compacting('minecraft:moss_block', Array(9).fill('minecraft:grass'))
    event.recipes.create.compacting('minecraft:tuff', ['create:powdered_obsidian', 'minecraft:gravel', Fluid.lava(15)])
    event.recipes.create.crushing([Item.of('create:copper_nugget').withChance(0.1), Item.of('create:zinc_nugget').withChance(0.1)], 'minecraft:blackstone')
    event.recipes.create.filling('minecraft:enchanted_golden_apple', ['minecraft:golden_apple', Fluid.of('create_enchantment_industry:experience', 1000)])
    event.recipes.create.filling('minecraft:lapis_lazuli', ['minecraft:blue_dye', Fluid.of('create_enchantment_industry:experience', 250)])
    event.recipes.create.filling('minecraft:sponge', ['#minecraft:wool', Fluid.of('create:potion', 250, { Potion: 'minecraft:water_breathing', Bottle: 'REGULAR' })])
    event.recipes.create.haunting('minecraft:coal', 'minecraft:charcoal')
    event.recipes.create.haunting('minecraft:end_stone', 'minecraft:polished_deepslate')
    event.recipes.create.haunting('minecraft:netherrack', 'minecraft:basalt')
    event.recipes.create.mixing('minecraft:dirt', ['minecraft:clay_ball', 'minecraft:sand', 'minecraft:bone_meal', Fluid.water(10)])
})
